name: Rust Check & Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master and tags branch
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_and_build:
    name: Check and Build

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up
        run: sudo apt install -y git clang curl libssl-dev llvm libudev-dev
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt,clippy
          override: true

      - name: cargo check --release
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --release
